### ISSUE TITLE
Excel file type is detected as "bin"

### ISSUE THREAD

**Issue by VadimPanov** [hey-red/Mime#26]
Steps to reproduce
- Right click and create a new Excel file
- use MimeGuesser.GuessFileType to detect file type

Actual result
Is detected as 'bin'

Expected result
detected as 'xlsx'

I attached the file to this issue

Note: If you open the file in excel and save it, the issue is gone (and size increased from 7kb to 8kb)

[New Microsoft Excel Worksheet (2).xlsx](https://github.com/hey-red/Mime/files/2357585/New.Microsoft.Excel.Worksheet.2.xlsx)

**Comment by hey-red** [comment]
File maybe too small to detect correct filetype. 
libmagic just check file headers(signatures) and if no match, returns default type(application/octet-stream with .bin extension)

**Comment by RezaRahmati** [comment]
Hey @hey-red 
Thanks for answer, 
It is interesting that when opening file in excel and just saving it, then it works.
Also we have other sample files (that we can't share it here because of sensitive data in it) that they have content and are not small, and same thing happens to them, so I doubt it's related to file size

**Comment by hey-red** [comment]
@RezaRahmati 
You can try to build your own magic.mgc, because I don't know when I can update .mgc file in that repo(it very old build).
magic.mgc is it compiled libmagic database, that uses these files as source 
https://github.com/file/file/tree/master/magic/Magdir
also, maybe you interesting how libmagic detect .xlsx
https://github.com/file/file/blob/master/magic/Magdir/msooxml 
this file has been recently updated and maybe that will help.

**Comment by hey-red** [comment]
Package has been updated.
