### ISSUE TITLE
Update File to version 5.41

### ISSUE THREAD

**Issue by andreas-eriksson** [hey-red/Mime#41]
Can File be updated to the latest released version?

https://github.com/file/file/releases/tag/FILE5_40

**Comment by andreas-eriksson** [comment]
Can I help in someway in order for this to get updated?

**Comment by andreas-eriksson** [comment]
A new version has been released.

https://github.com/file/file/releases/tag/FILE5_41

**Comment by andreas-eriksson** [comment]
Ping @hey-red

**Comment by hey-red** [comment]
Hello! Tomorrow I will try to rewrite a script to build libmagic and push new packages.
The main problem of updating - it's cross platform build for OSX. Ofcourse we can just take builds from homebrew or another sources.. but I cant investige that it works.

Anyway project needs to be rewritten(new .NET api) and allow for developers plug their own libmagic builds.

**Comment by andreas-eriksson** [comment]
Thank you very much. 👍

**Comment by hey-red** [comment]
[3.3.0](https://www.nuget.org/packages/Mime/3.3.0) is now available.
I didn't do deep tests, but all basic tests passed(on windows). 

OSX binaries remained at 5.38, because I have no idea how to get them from https://github.com/Homebrew/homebrew-core/pkgs/container/core%2Flibmagic/9275765?tag=5.41
I have no reports from mac users, and maybe dylib from repo is no longer works on new OSX.

**Comment by andreas-eriksson** [comment]
Seems to work fine for me 👍 Thanks again.
