### ISSUE TITLE
3.6.0 - libmagic-1.dll flagged as virus

### ISSUE THREAD

**Issue by Krudor** [hey-red/Mime#55]
libmagic-1.dll in version 3.6.0 is being blocked by Brave browser, as well as Bitdefender from being detected as a virus.

VirusTotal scan: https://www.virustotal.com/gui/file/3fdb96bc6510912ea6b6be4dfb6d316fed8c3b971fbf7d79fb134a30e354d948/detection

**Comment by hey-red** [comment]
Hmm, interesting..
I think is just false positive, because x64 dll passes all tests 
https://www.virustotal.com/gui/file/6b0ce1425f466b91f5fa2c38c29d5d6ef759f188b9dd9c638d1cbe991250807e/detection

Build script for windows can be found here https://github.com/hey-red/Libmagic-Build/blob/master/windows/libmagic_win.sh
